package bfst21.osm;

public enum Tag {
	BUILDING, COASTLINE, CYCLEWAY, EMPTY, FOOTWAY, HIGHWAY, JUNCTION, LIVING_STREET, MOTORWAY, PARK, PATH, PEDESTRIAN, PRIMARY, RESIDENTIAL, ROAD, SECONDARY, SERVICE, TERRITORIALBORDER, TERTIARY, TRACK, TRUNK, UNCLASSIFIED, WATER
}
