package bfst21.osm;

public enum Tag {
    BUILDING, CEMETERY, COASTLINE, CYCLEWAY, /*FARMLAND,*/ FOOTWAY, FOREST, GRASS, GRAVE_YARD, GRASSLAND, JUNCTION,
    LIVING_STREET, MEADOW, MOTORWAY, ORCHARD, PARK, PATH, PEDESTRIAN, PRIMARY, RESIDENTIAL, ROAD, SCRUB, SECONDARY,
    SERVICE, TERRITORIALBORDER, TERTIARY, TRACK, TRUNK, UNCLASSIFIED, WATER
}
