package bfst21.pathfinding;

public enum Direction {
    ARRIVAL, CONTINUE_AHEAD, FOLLOW, TURN_RIGHT, TURN_LEFT, TURN_INTO_ROUNDABOUT, TAKE_EXIT_ROUNDABOUT, TAKE_FIRST_EXIT_ROUNDABOUT, TAKE_SECOND_EXIT_ROUNDABOUT, TAKE_THIRD_EXIT_ROUNDABOUT, TAKE_FOURTH_EXIT_ROUNDABOUT, TAKE_FIFTH_EXIT_ROUNDABOUT, TAKE_SIXTH_EXIT_ROUNDABOUT, TAKE_SEVENTH_EXIT_ROUNDABOUT, TAKE_EIGTH_EXIT_ROUNDABOUT,;
}
